// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package gqlgen

import (
	"time"

	"github.com/99designs/gqlgen/graphql"

	"github.com/stegoer/server/ent"
	"github.com/stegoer/server/pkg/util"
)

type Auth struct {
	Token   string    `json:"token"`
	Expires time.Time `json:"expires"`
}

type CreateUserPayload struct {
	User *ent.User `json:"user"`
	Auth *Auth     `json:"auth"`
}

type DecodeImageInput struct {
	EncryptionKey *string        `json:"encryptionKey"`
	Upload        graphql.Upload `json:"upload"`
}

type DecodeImagePayload struct {
	Data string `json:"data"`
}

type EncodeImageInput struct {
	Data             string         `json:"data"`
	EncryptionKey    *string        `json:"encryptionKey"`
	LsbUsed          int            `json:"lsbUsed"`
	Channel          util.Channel   `json:"channel"`
	EvenDistribution bool           `json:"evenDistribution"`
	Upload           graphql.Upload `json:"upload"`
}

type EncodeImagePayload struct {
	File *FileType `json:"file"`
}

type FileType struct {
	Name    string `json:"name"`
	Content string `json:"content"`
}

type ImagesConnection struct {
	TotalCount int              `json:"totalCount"`
	PageInfo   *ent.PageInfo    `json:"pageInfo"`
	Edges      []*ent.ImageEdge `json:"edges"`
}

type Login struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginPayload struct {
	User *ent.User `json:"user"`
	Auth *Auth     `json:"auth"`
}

type NewUser struct {
	Username string `json:"username"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type OverviewPayload struct {
	User *ent.User `json:"user"`
}

type RefreshTokenInput struct {
	Token string `json:"token"`
}

type RefreshTokenPayload struct {
	User *ent.User `json:"user"`
	Auth *Auth     `json:"auth"`
}

type UpdateUser struct {
	Username *string `json:"username"`
	Email    *string `json:"email"`
	Password *string `json:"password"`
}

type UpdateUserPayload struct {
	User *ent.User `json:"user"`
}
