version: 2
updates:
  # Maintain dependencies for GitHub Actions.
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for github.com/stegoer/server Go Module.
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily

  # Maintain dependencies for github.com/stegoer/server/tools Go Module.
  - package-ecosystem: gomod
    directory: /tools
    schedule:
      interval: daily
