repos:
  - repo: local
    hooks:
      - id: make-fmt
        name: Make fmt
        entry: make fmt
        language: system
        files: \.go$
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.0
    hooks:
      - id: prettier
        name: Prettier
        files: "\\.(graphql|graphqls|json|md|js|jsx|ts|tsx|yaml|yml|css|less|scss)$"
  - repo: https://github.com/golangci/golangci-lint
    rev: v1.45.0
    hooks:
      - id: golangci-lint
        name: golangci-lint
        files: \.go$
