// Code generated by "stringer -type=ColorChannel"; DO NOT EDIT.

package schema

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[RED-0]
	_ = x[GREEN-1]
	_ = x[BLUE-2]
	_ = x[RED_GREEN-3]
	_ = x[RED_BLUE-4]
	_ = x[GREEN_BLUE-5]
	_ = x[RED_GREEN_BLUE-6]
}

const _ColorChannel_name = "REDGREENBLUERED_GREENRED_BLUEGREEN_BLUERED_GREEN_BLUE"

var _ColorChannel_index = [...]uint8{0, 3, 8, 12, 21, 29, 39, 53}

func (i ColorChannel) String() string {
	if i < 0 || i >= ColorChannel(len(_ColorChannel_index)-1) {
		return "ColorChannel(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ColorChannel_name[_ColorChannel_index[i]:_ColorChannel_index[i+1]]
}
