// Code generated by entc, DO NOT EDIT.

package ent

import "context"

func (i *Image) User(ctx context.Context) (*User, error) {
	result, err := i.Edges.UserOrErr()
	if IsNotLoaded(err) {
		result, err = i.QueryUser().Only(ctx)
	}
	return result, MaskNotFound(err)
}

func (u *User) Images(ctx context.Context) ([]*Image, error) {
	result, err := u.Edges.ImagesOrErr()
	if IsNotLoaded(err) {
		result, err = u.QueryImages().All(ctx)
	}
	return result, err
}
