name: Docs

on:
  push:
    branches:
      - master

jobs:
  docs:
    name: docs
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "v16.14.0"
          cache: "npm"
          cache-dependency-path: client/package-lock.json

      - name: Install packages
        run: cd client && npm ci

      - name: Build Docs
        run: cd client && npm run build-docs

      - name: Deploy Docs
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: client/docs
